//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.Service.Infrastructure.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextDictionary() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Invoice.Service.Infrastructure.Utils.Resources.TextDictionary", typeof(TextDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido generar la Linea de Captura.
        /// </summary>
        public static string ApiFinanzas_Error {
            get {
                return ResourceManager.GetString("ApiFinanzas_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} no cumple con el fomato correcto.
        /// </summary>
        public static string Field_format_v {
            get {
                return ResourceManager.GetString("Field_format_v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es excede el tamaño máximo de caracteres {1}.
        /// </summary>
        public static string Field_maxlenght_v {
            get {
                return ResourceManager.GetString("Field_maxlenght_v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es requerido.
        /// </summary>
        public static string Field_required_v {
            get {
                return ResourceManager.GetString("Field_required_v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} se encuentra deshabilitado para realizar esta acción.
        /// </summary>
        public static string Module_disabled {
            get {
                return ResourceManager.GetString("Module_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El {0} ya existe.
        /// </summary>
        public static string Module_Exist_v {
            get {
                return ResourceManager.GetString("Module_Exist_v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo completar la operación.
        /// </summary>
        public static string Msg_not_found {
            get {
                return ResourceManager.GetString("Msg_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacipón realizada con éxito.
        /// </summary>
        public static string Msg_success_found {
            get {
                return ResourceManager.GetString("Msg_success_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} no encontrado..
        /// </summary>
        public static string Not_found {
            get {
                return ResourceManager.GetString("Not_found", resourceCulture);
            }
        }
    }
}
